version: 2.1

orbs:
  architect: giantswarm/architect@4.33.0

workflows:
  go-build:
    jobs:
      - architect/go-build:
          name: go-build
          binary: heartbeatctl
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/go-build:
          name: go-build-heartbeatctl-linux-amd64
          binary: build/heartbeatctl-linux-amd64/heartbeatctl
          os: linux
          filters:
            branches:
              only: main
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/go-build:
          name: go-build-heartbeatctl-darwin-amd64
          binary: build/heartbeatctl-darwin-amd64/heartbeatctl
          os: darwin
          filters:
            branches:
              only: main
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-quay
          context: "architect"
          image: quay.io/giantswarm/heartbeatctl
          username_envar: QUAY_USERNAME
          password_envar: QUAY_PASSWORD
          requires:
            - go-build
          filters:
            # Needed to trigger job also on git tag.
            tags:
              only: /^v.*/

      - architect/push-to-docker:
          name: push-to-docker
          context: "architect"
          image: "docker.io/giantswarm/heartbeatctl"
          username_envar: "DOCKER_USERNAME"
          password_envar: "DOCKER_PASSWORD"
          requires:
            - go-build
          filters:
            tags:
              only: /^v.*/
